### ISSUE TITLE
Build cordova project issue with the plugin

### ISSUE THREAD

**Issue by hazem-tamimi** [jaypratapsingh/GoogleDrive#1]
after adding the plugin to my cordova project and build the project an error appear ,see below:

:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:23: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.Drive;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:24: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.DriveApi;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:25: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.DriveContents;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:26: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.DriveFile;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:27: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.DriveFolder;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:28: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.DriveId;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:29: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.DriveResource;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:30: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.MetadataChangeSet;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:31: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.OpenFileActivityBuilder;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:32: error: package com.google.android.gms.drive.metadata does not exist
import com.google.android.gms.drive.metadata.CustomPropertyKey;
                                            ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:62: error: cannot find symbol
    private DriveId mSelectedFileDriveId;
            ^
  symbol:   class DriveId
  location: class GoogleDrive
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:321: error: package DriveFolder does not exist
    final private ResultCallback<DriveFolder.DriveFileResult> fileCallback = new
                                            ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:92: error: cannot find symbol
                    .addScope(Drive.SCOPE_FILE)
                              ^
  symbol:   variable Drive
  location: class GoogleDrive
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:91: error: cannot find symbol
                    .addApi(Drive.API)
                            ^
  symbol:   variable Drive
  location: class GoogleDrive
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:157: error: cannot find symbol
                    DriveFile file = Drive.DriveApi.getFile(mGoogleApiClient,mSelectedFileDriveId);
                    ^
  symbol: class DriveFile
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:157: error: package Drive does not exist
                    DriveFile file = Drive.DriveApi.getFile(mGoogleApiClient,mSelectedFileDriveId);
                                          ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:158: error: package DriveResource does not exist
                    DriveResource.MetadataResult mdRslt = file.getMetadata(mGoogleApiClient).await();
                                 ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:252: error: package DriveApi does not exist
                        .setResultCallback(new ResultCallback<DriveApi.DriveContentsResult>() {
                                                                      ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:255: error: package DriveApi does not exist
                            public void onResult(DriveApi.DriveContentsResult result) {
                                                         ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:286: error: cannot find symbol
                                    CustomPropertyKey approvalPropertyKey = new CustomPropertyKey("approved", CustomPropertyKey.PUBLIC);
                                    ^
  symbol: class CustomPropertyKey
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:286: error: cannot find symbol
                                    CustomPropertyKey approvalPropertyKey = new CustomPropertyKey("approved", CustomPropertyKey.PUBLIC);
                                                                                ^
  symbol: class CustomPropertyKey
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:286: error: cannot find symbol
                                    CustomPropertyKey approvalPropertyKey = new CustomPropertyKey("approved", CustomPropertyKey.PUBLIC);
                                                                                                              ^
  symbol: variable CustomPropertyKey
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:287: error: cannot find symbol
                                    MetadataChangeSet metadataChangeSet = new MetadataChangeSet.Builder()
                                    ^
  symbol: class MetadataChangeSet
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:287: error: package MetadataChangeSet does not exist
                                    MetadataChangeSet metadataChangeSet = new MetadataChangeSet.Builder()
                                                                                               ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:291: error: package Drive does not exist
                                    Drive.DriveApi.getRootFolder(mGoogleApiClient)
                                         ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:251: error: package Drive does not exist
                Drive.DriveApi.newDriveContents(mGoogleApiClient)
                     ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:322: error: package DriveFolder does not exist
            ResultCallback<DriveFolder.DriveFileResult>() {
                                      ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:324: error: package DriveFolder does not exist
                public void onResult(DriveFolder.DriveFileResult result) {
                                                ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:338: error: cannot find symbol
                .setMimeType(new String[]{ DriveFolder.MIME_TYPE, "application/pdf" })
                                           ^
  symbol:   variable DriveFolder
  location: class GoogleDrive
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:336: error: package Drive does not exist
        IntentSender intentSender = Drive.DriveApi
                                         ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:365: error: cannot find symbol
                mSelectedFileDriveId = (DriveId) data.getParcelableExtra(
                                        ^
  symbol:   class DriveId
  location: class GoogleDrive
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:366: error: cannot find symbol
                        OpenFileActivityBuilder.EXTRA_RESPONSE_DRIVE_ID);
                        ^
  symbol:   variable OpenFileActivityBuilder
  location: class GoogleDrive
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
32 errors
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14.759 secs
Error: /Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:23: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.Drive;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:24: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.DriveApi;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:25: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.DriveContents;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:26: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.DriveFile;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:27: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.DriveFolder;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:28: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.DriveId;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:29: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.DriveResource;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:30: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.MetadataChangeSet;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:31: error: package com.google.android.gms.drive does not exist
import com.google.android.gms.drive.OpenFileActivityBuilder;
                                   ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:32: error: package com.google.android.gms.drive.metadata does not exist
import com.google.android.gms.drive.metadata.CustomPropertyKey;
                                            ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:62: error: cannot find symbol
    private DriveId mSelectedFileDriveId;
            ^
  symbol:   class DriveId
  location: class GoogleDrive
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:321: error: package DriveFolder does not exist
    final private ResultCallback<DriveFolder.DriveFileResult> fileCallback = new
                                            ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:92: error: cannot find symbol
                    .addScope(Drive.SCOPE_FILE)
                              ^
  symbol:   variable Drive
  location: class GoogleDrive
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:91: error: cannot find symbol
                    .addApi(Drive.API)
                            ^
  symbol:   variable Drive
  location: class GoogleDrive
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:157: error: cannot find symbol
                    DriveFile file = Drive.DriveApi.getFile(mGoogleApiClient,mSelectedFileDriveId);
                    ^
  symbol: class DriveFile
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:157: error: package Drive does not exist
                    DriveFile file = Drive.DriveApi.getFile(mGoogleApiClient,mSelectedFileDriveId);
                                          ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:158: error: package DriveResource does not exist
                    DriveResource.MetadataResult mdRslt = file.getMetadata(mGoogleApiClient).await();
                                 ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:252: error: package DriveApi does not exist
                        .setResultCallback(new ResultCallback<DriveApi.DriveContentsResult>() {
                                                                      ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:255: error: package DriveApi does not exist
                            public void onResult(DriveApi.DriveContentsResult result) {
                                                         ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:286: error: cannot find symbol
                                    CustomPropertyKey approvalPropertyKey = new CustomPropertyKey("approved", CustomPropertyKey.PUBLIC);
                                    ^
  symbol: class CustomPropertyKey
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:286: error: cannot find symbol
                                    CustomPropertyKey approvalPropertyKey = new CustomPropertyKey("approved", CustomPropertyKey.PUBLIC);
                                                                                ^
  symbol: class CustomPropertyKey
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:286: error: cannot find symbol
                                    CustomPropertyKey approvalPropertyKey = new CustomPropertyKey("approved", CustomPropertyKey.PUBLIC);
                                                                                                              ^
  symbol: variable CustomPropertyKey
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:287: error: cannot find symbol
                                    MetadataChangeSet metadataChangeSet = new MetadataChangeSet.Builder()
                                    ^
  symbol: class MetadataChangeSet
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:287: error: package MetadataChangeSet does not exist
                                    MetadataChangeSet metadataChangeSet = new MetadataChangeSet.Builder()
                                                                                               ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:291: error: package Drive does not exist
                                    Drive.DriveApi.getRootFolder(mGoogleApiClient)
                                         ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:251: error: package Drive does not exist
                Drive.DriveApi.newDriveContents(mGoogleApiClient)
                     ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:322: error: package DriveFolder does not exist
            ResultCallback<DriveFolder.DriveFileResult>() {
                                      ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:324: error: package DriveFolder does not exist
                public void onResult(DriveFolder.DriveFileResult result) {
                                                ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:338: error: cannot find symbol
                .setMimeType(new String[]{ DriveFolder.MIME_TYPE, "application/pdf" })
                                           ^
  symbol:   variable DriveFolder
  location: class GoogleDrive
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:336: error: package Drive does not exist
        IntentSender intentSender = Drive.DriveApi
                                         ^
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:365: error: cannot find symbol
                mSelectedFileDriveId = (DriveId) data.getParcelableExtra(
                                        ^
  symbol:   class DriveId
  location: class GoogleDrive
/Users/Guest_User/code/NetBeansProjects/traqpath_GDrive/platforms/android/src/com/jp/googledrive/GoogleDrive.java:366: error: cannot find symbol
                        OpenFileActivityBuilder.EXTRA_RESPONSE_DRIVE_ID);
                        ^
  symbol:   variable OpenFileActivityBuilder
  location: class GoogleDrive
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
32 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by jaypratapsingh** [comment]
Please add the 'com.google.android.gms:play-services-drive:9.8.0' dependencies in your gradle file
